name: Python Linting and Spell Check

on:
  pull_request:
    branches:
      - main

jobs:
  validate-python-and-spelling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Verificar código Python com flake8
      - name: Run Python linting with flake8
        if: ${{ contains(github.event.pull_request.changed_files, '.py') }}
        run: |
          echo "Running flake8 for Python linting..."
          pip install flake8
          flake8 . --exclude=.venv --max-line-length=88  # Ajuste o tamanho da linha conforme necessário

      # Verificar ortografia em arquivos Markdown e Texto com codespell
      - name: Run spell check on documentation
        if: ${{ contains(github.event.pull_request.changed_files, '.md') || contains(github.event.pull_request.changed_files, '.txt') }}
        run: |
          echo "Running spell check on documentation files..."
          pip install codespell
          codespell --ignore-words-list="foobar,custom" .